import "./globals.css";
import AppLayout from "./components/AppLayout"; // adjust a path if needed

export const metadata = {
  title: "CEH Quiz App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppLayout>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}
